Branch 1.0.1
eHarmony/spotz pull request #36
Opened 2016-09-20 20:47 UTC by vsuthichai

2016-09-20 22:13 UTC, jmorra commented on README.md
> +val stopStrategy = StopStrategy.stopAfterMaxTrials(100000)
Why hardcode?

2016-09-20 22:17 UTC, jmorra commented on vw/src/main/scala/com/eharmony/spotz/objective/vw/VwFunctions.scala
> +    vwParamMap.get("cb") match {
I would bet this isn't general enough.  I would try `--cb_adf`, `--cb_explore`, and `--cb_explore_adf`.

2016-09-20 22:20 UTC, jmorra requested changes
I would think that you could generalize this more to accept an `Option[String]` for required cache generation parameters.

2016-09-21 00:28 UTC, vsuthichai commented on README.md
> +val stopStrategy = StopStrategy.stopAfterMaxTrials(100000)
It's a readme.  I made it so that copying that code into a REPL would work.

2016-09-21 05:58 UTC, vsuthichai commented on vw/src/main/scala/com/eharmony/spotz/objective/vw/VwFunctions.scala
> +    vwParamMap.get("cb") match {
I've updated the code to account for these parameters.

2016-09-21 20:29 UTC, jmorra approved these changes
This looks good as now it just passes the train args through.

2016-09-21 20:30 UTC, merged